apiVersion: v1
kind: Service
metadata:
  name: service-polices
  namespace: luc-assure
  labels:
    app: service-polices
spec:
  type: LoadBalancer
  selector:
    app: service-polices
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
